version: '3'
services:
  db:
    image: postgis/postgis:13-master
    command: postgres -c max_locks_per_transaction=100
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSWORD: dhis
    # volumes:
    # - ./config/:/docker-entrypoint-initdb.d/
    volumes:
      - ./data:/data
    ports:
    - "5432:5432"
  web:
    image: dhis2/core:2.35.10
    volumes:
    - ./config/dhis2_home:/DHIS2_home
    ports:
    - "8080:8080"
    # environment:
    # - WAIT_FOR_DB_CONTAINER=db:5432 -t 0
    depends_on:
    - db
